"""Init_con_UUIDs

Revision ID: 6c541e45549b
Revises: 
Create Date: 2026-05-02 17:52:43.964558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c541e45549b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fincas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finca_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animales_codigo'), 'animales', ['codigo'], unique=True)
    op.create_table('compradores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finca_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quincenas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finca_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendedores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finca_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entregas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=False),
    sa.Column('quincena_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('litros', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['comprador_id'], ['compradores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quincena_id'], ['quincenas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('VACUNACION', 'ENFERMEDAD', 'PARTO', 'CELO', 'MONTA', 'SERVICIO', 'VENDIDO', 'MUERTE', name='tipo_evento_enum'), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precios_leche',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quincena_id', sa.Integer(), nullable=False),
    sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['quincena_id'], ['quincenas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produccion_vendedor_diaria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('litros', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produccion_vendedor_diaria')
    op.drop_table('precios_leche')
    op.drop_table('eventos')
    op.drop_table('entregas')
    op.drop_table('vendedores')
    op.drop_table('quincenas')
    op.drop_table('compradores')
    op.drop_index(op.f('ix_animales_codigo'), table_name='animales')
    op.drop_table('animales')
    op.drop_table('fincas')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
